# Generated by Django 5.0.2 on 2024-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('mqtt_topic', models.CharField(max_length=30)),
            ],
        ),
    ]
